# compytation on numpy arrays
* > computation of numpy arrays can be very fast or it can be very slow.
* > The key to making it very fast it to use

In [1]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
xy=np.add(x,y)
print(xy)

[ 6  8 10 12]


In [6]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
xy=np.subtract(x,y)
print(xy)

[-4 -4 -4 -4]


In [5]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
xy=np.multiply(x,y)
print(xy)

[ 5 12 21 32]


In [7]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
xy=np.divide(x,y)
print(xy)

[0.2        0.33333333 0.42857143 0.5       ]


In [9]:
x=np.array([1,-2,3,-4,-2,-3,2,7,-8])
xy=np.absolute(x)
print(xy)

[1 2 3 4 2 3 2 7 8]


In [11]:
x=np.array([1,-2,3,-4,-2,-3,2,7,-8])
np.exp(x)
np.exp2(x)
np.log(x)
np.log2(x)

C:\Users\aarya\AppData\Local\Temp\ipykernel_10384\3683172169.py:4: RuntimeWarning: invalid value encountered in log
  np.log(x)
C:\Users\aarya\AppData\Local\Temp\ipykernel_10384\3683172169.py:5: RuntimeWarning: invalid value encountered in log2
  np.log2(x)


array([0.        ,        nan, 1.5849625 ,        nan,        nan,
              nan, 1.        , 2.80735492,        nan])

# Advanced Ufunc features
* > 1. Specifying calculation

In [12]:
import numpy as np
x=np.arange(2,20,2)
print(x)
z=np.empty((9))
print(z)
print(np.multiply(x,10,out=z))

[ 2  4  6  8 10 12 14 16 18]
[4.9e-324      nan 1.5e-323      nan      nan      nan 9.9e-324 3.5e-323
      nan]
[ 20.  40.  60.  80. 100. 120. 140. 160. 180.]


* > 2. Aggregation (Reduce method)
    > - If you like to reduce an array with a particular operation , we can use the reduce method of any ufunc.
    > - A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [16]:
x=np.arange(1,11)
print(x)
np.add.reduce(x)

[ 1  2  3  4  5  6  7  8  9 10]


np.int64(55)

In [17]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [44]:
y=np.arange(1,11)
np.sum

<function sum at 0x000001FBE21EA5F0>

In [23]:
np.prod(y)

np.int64(3628800)

In [24]:
np.cumsum(y)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [25]:
np.cumprod(y)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [26]:
np.mean(y)

np.float64(5.5)

In [27]:
np.std(y)

np.float64(2.8722813232690143)

In [28]:
np.var(y)

np.float64(8.25)

In [29]:
np.max(y)

np.int64(10)

In [30]:
np.argmin(y)

np.int64(0)

In [31]:
np.argmax(y)

np.int64(9)

In [32]:
np.median(y)

np.float64(5.5)

In [ ]:
np.any(y)

np.True_

In [37]:
np.all(y)

np.True_

# Q). Create a matrix of 10*10. Extract a single row.

In [ ]:
# create a matrix of 10*10, extract a single column
import numpy as np
