# Numpy -> Numerical Python

1. Numpy is one of the most important foundational package for numerical computing in python.
2. It is an open source python package, that is widely used in science and engineering.
3. The Numpy library contains multi-dimensional array data structure, such as homogenous , n-dimensional (ND) array and a large library of function that operates efficiently on these data structures.

# Why do we use python Numpy?
* We use python Numpy array, instead of list beacuse of the below three reasons:-
  > - less memory
  > - fast
  > - convenient to undertand.
  > - vectorization (way faster than loop in list).

# Why not Python in-built data structure list ?
* A python list stores elements + meta data + pointers -> thus using more memory.
* A Numpy array stores data in a continuous block -> more efficeint and compact.


# Difference between List and Array
* List is an in-built data structure whereas Numpy is a python Library.
* List is slower. Array is faster.
* List store heterogenous data, Array stores Homogenous data structure.
* Numpy library contains multi-dimensional array data structure. Whereas List conatain singke dimensional data structure.

In [8]:
import numpy as np

In [10]:
x=np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
np.__version__

'2.3.4'

In [9]:
arr=np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [12]:
arr=np.array(100)
print(arr)
print(arr.ndim)

100
0


In [13]:
oneD=np.array([1, 2, 3, 4,5])
print(oneD)

print(oneD.ndim)
print(oneD.shape)
print(oneD.size)
print(oneD.itemsize)
print(oneD.dtype)

[1 2 3 4 5]
1
(5,)
5
8
int64


In [14]:
twoD=np.array([[1, 2, 3], [4, 5, 6]])
print(twoD)

print(twoD.ndim)
print(twoD.shape)
print(twoD.size)
print(twoD.itemsize)
print(twoD.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


In [15]:
import numpy as np
threeD=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
m=np.ones(range(0,5))
m

array([], shape=(0, 1, 2, 3, 4), dtype=float64)

In [17]:
u=np.arange(0, 10, 2)
u

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [41]:
import sys as sy

In [56]:
list1=[1, 2, 3, 4, 5, 6, 7, 8, 9]
print(sy.getsizeof(list1))

136


In [57]:
arr=np.array(list1)
print(arr.size*arr.itemsize)
print(arr.nbytes)

72
72


In [58]:
import time as t

In [60]:
l1=range(1,100000)
l2=range(1,100000)
A1=np.array(l1)
A2=np.array(l2)

In [61]:
start=t.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((t.time()-start)*1000)

14.16015625
