# Numpy -> Numerical Python

1. Numpy is one of the most important foundational package for numerical computing in python.
2. It is an open source python package, that is widely used in science and engineering.
3. The Numpy library contains multi-dimensional array data structure, such as homogenous , n-dimensional (ND) array and a large library of function that operates efficiently on these data structures.

# Why do we use python Numpy?
* We use python Numpy array, instead of list beacuse of the below three reasons:-
  > - less memory
  > - fast
  > - convenient to undertand.
  > - vectorization (way faster than loop in list).

# Why not Python in-built data structure list ?
* A python list stores elements + meta data + pointers -> thus using more memory.
* A Numpy array stores data in a continuous block -> more efficeint and compact.


# Difference between List and Array
* List is an in-built data structure whereas Numpy is a python Library.
* List is slower. Array is faster.
* List store heterogenous data, Array stores Homogenous data structure.
* Numpy library contains multi-dimensional array data structure. Whereas List conatain singke dimensional data structure.

In [2]:
import numpy as np

In [10]:
x=np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
np.__version__

'2.3.4'

In [9]:
arr=np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [12]:
arr=np.array(100)
print(arr)
print(arr.ndim)

100
0


In [13]:
oneD=np.array([1, 2, 3, 4,5])
print(oneD)

print(oneD.ndim)
print(oneD.shape)
print(oneD.size)
print(oneD.itemsize)
print(oneD.dtype)

[1 2 3 4 5]
1
(5,)
5
8
int64


In [14]:
twoD=np.array([[1, 2, 3], [4, 5, 6]])
print(twoD)

print(twoD.ndim)
print(twoD.shape)
print(twoD.size)
print(twoD.itemsize)
print(twoD.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


In [15]:
import numpy as np
threeD=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
m=np.ones(range(0,5))
m

array([], shape=(0, 1, 2, 3, 4), dtype=float64)

In [17]:
u=np.arange(0, 10, 2)
u

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [41]:
import sys as sy

In [56]:
list1=[1, 2, 3, 4, 5, 6, 7, 8, 9]
print(sy.getsizeof(list1))

136


In [57]:
arr=np.array(list1)
print(arr.size*arr.itemsize)
print(arr.nbytes)

72
72


In [58]:
import time as t

In [60]:
l1=range(1,100000)
l2=range(1,100000)
A1=np.array(l1)
A2=np.array(l2)

In [61]:
start=t.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((t.time()-start)*1000)

14.16015625


# Vectorization:
> It means performing operations on entire arrays at once instead of using python loops.

> It is fast as Numpy uses optimized C only internally. -> Works

In [3]:
l1=np.array([1,2,3,4,5])
l2=np.array([1,2,3,4,5])
print(l1+l2)

[ 2  4  6  8 10]


In [4]:
l1=[1,2,3,4,5]
l2=[1,2,3,4,5]
print(l1+l2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


#WITH LISTS, YOU DO OPERATIONS ELEMEMT BY ELEMENT. -> SLOW

#NUMPY ALLOWS ELEMENT WISE OPERATIONS WITHOUT EXPLICIT LOOPS. -> MUCH FASTER

In [6]:
import time as t
arr=np.arange(100000)
lst=[x for x in range(100000)]
start=t.time()
lst2=[x*2 for x in lst]
end=t.time()
print(end - start)

0.005723714828491211


# --> Broadcasting
* -> Operations between different shape arrays
* -> numpy automatically expands the smaller array (without copying), so shapes beome compatible.

In [7]:
a=np.array([1,2,3,4,5])
b=5
print(a+b)

[ 6  7  8  9 10]


In [11]:
arr=np.array([1, 2, 3])
vec=np.array([[1], [2], [3]])
print(arr+vec)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# How to use a python numpy to generate random number
* Random Module
* The random module  in Numpy packag contains many function for generation of random numbers

In [14]:
import random
x=np.random.rand(10)
print(x)
y=np.random.randrange(0, 10)
print(y)

[0.47469713 0.68596618 0.39035052 0.38156445 0.46131647 0.95642184
 0.06803009 0.3529698  0.21800483 0.55591101]


AttributeError: module 'numpy.random' has no attribute 'randrange'

# --> Choice method

In [6]:
import numpy as np
import random
rng=np.random.default_rng()
x=np.random.choice([1,2,3,4,5,6,7,8])
y=rng.choice([1,2,3,4,5,6,7,8])
print(x)
print(y)

8
7


In [10]:
x=np.array([10,23,45,67,89])
print(x[2])
x[2]

45


np.int64(45)

In [15]:
#in multidimensional array, you can specify a comma separated 
y=np.array([[12,23,34], [2,4,67]])
# Method1
print(y[0,2])
# Method2
print(y[0][2])

34
34


In [24]:
x=np.array([10,23,45,67,89])
x[1:4]

array([23, 45, 67])

In [ ]:
y=np.array([[12,23,34], [2,4,67], [1,1,1], [2,2,2]])
y[1:]

array([[ 2,  4, 67],
       [ 1,  1,  1],
       [ 2,  2,  2]])

In [23]:
y[-1:]

array([[2, 2, 2]])

In [26]:
y[-3:-1]

array([[ 2,  4, 67],
       [ 1,  1,  1]])

In [27]:
import numpy as np
arr=np.array([1,2,3,4])
s=arr[1:3]
s[0]=100
print(arr)
print(s)
print(s.base)

[  1 100   3   4]
[100   3]
[  1 100   3   4]


# Fancy Indexing
* Fancy indexing is like the simple indexing we've already seen, but we pass array of indices in place of single scalars

In [3]:
import numpy as np
import random
xy=np.random.randint(2,100,size=(10,10))
xy1=np.random.rand(10,10)
print(xy)
print(xy1)

[[52  7 99 70 90 36 57 64 78 10]
 [43 70 51 93 50 31 80 88 86 50]
 [55 78 33 53 79  9  2 13 23 17]
 [39 97 56 25 73 76 60 74 86 81]
 [ 2 82 33 41  6 10 87 53 65 36]
 [ 3 91 11 33 58 14 39 99 38 15]
 [97 99 83 85 60 33 54 16 32 91]
 [88 79 22 18 60 53 90 96 51  4]
 [67 41  7 17 10 92 52 10 47 98]
 [80 44 10 61 96 60 46 76 31 53]]
[[0.77241919 0.53267572 0.33175769 0.20683301 0.85617315 0.55785148
  0.06427428 0.53093442 0.31181751 0.6395748 ]
 [0.94827241 0.70032869 0.94223439 0.25408494 0.25252564 0.96517559
  0.23087605 0.0982685  0.86082229 0.17855934]
 [0.88224379 0.63549887 0.09108704 0.92602004 0.67453997 0.65590755
  0.55052388 0.56600554 0.06749393 0.9583305 ]
 [0.55994    0.45474334 0.21323136 0.23003789 0.68687425 0.47424068
  0.3991859  0.62422821 0.94358638 0.51949366]
 [0.77172853 0.59538455 0.61978675 0.579752   0.26156133 0.16917907
  0.87085044 0.34519147 0.29232282 0.22390276]
 [0.20845063 0.42533612 0.8753725  0.45723383 0.12504144 0.71520539
  0.41675053 0.24909027 0.

In [5]:
n=np.arange(1,13)
print(n)
x=n.reshape((3,4))
print(x)
print(x.reshape((2,6)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
n=np.arange(1,13)
n[5]=20
print(n)
id(n)

[ 1  2  3  4  5 20  7  8  9 10 11 12]


1726969803568

In [8]:
n=np.arange(1,13).base
print(n)

None


# check it returns a copy or view 

In [2]:
import numpy as np
n=np.arange(1,13)
n[5]=20
print(n)
id(n)

[ 1  2  3  4  5 20  7  8  9 10 11 12]


2399235978032

In [5]:
y=n.reshape((4,3)).base
print(y)
id(y)

[ 1  2  3  4  5 20  7  8  9 10 11 12]


2399235978032

In [6]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
x=arr.view()
y=arr.copy()
arr[0]=42
print(arr)
id(arr)

[42  2  3  4  5  6  7  8  9 10 11 12]


2399238336560

In [7]:
print(x)
print(id(x))
print(x.base)

[42  2  3  4  5  6  7  8  9 10 11 12]
2399238336464
[42  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
print(y)
print(id(y))
print(y.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
2399238335984
None


# Check if array owns its data
* > As mentioned above,copies owns the data,and views does not own the data,but how can we check this?
    * Every Numpy array has the attribute base that returns None if the array owns the data
otherwise,the base attribute refers to the orignal object

In [ ]:
arr=np.random

# Flattening of Array

In [9]:
x=np.random.randint(10, size=(2,3))
print(x)
x.reshape(-1)

[[5 6 5]
 [3 2 4]]


array([5, 6, 5, 3, 2, 4], dtype=int32)

# Transpose of array

In [10]:
x=np.arange(1,10).reshape((3,3))
print(x)
x.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Rotation of Array
* > the rot90() function is used to rotate an array by 90 degrees in the plane specified by axes
* > Syntax:
    * numpy.rot90(m,k=1,axes=(0,1))
    * m is array of two or more dimension
    * k=number of times the array is rotational by 90 degree
axes yhr array is rotated in the plane defined by the axes.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
x=x.reshape(3,3)
print(np.rot90(x,k=1,axes=(1,0)))

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [2]:
import numpy as np
x=np.array([[1,1,1],[2,2,2]])
y=np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=1)

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5]])

# np.vstack

In [3]:
x=np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.array([[4,4,4],[5,5,5]])
np.vstack([x,y])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

# np.hstack

In [4]:
x=np.array([[1,1,1],[2,2,2]])
y=np.array([[4,4,4],[5,5,5]])
np.hstack([x,y])

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5]])

# Splitting of Arrays
* > np.vsplit
* > np.hsplit

In [5]:
x=np.arange(1,13)
print(x)
np.split(x,4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [6]:
x=np.arange(1,13)
print(x)
np.split(x,4, axis=0)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [10]:
x=np.arange(1,10)
print(x)
np.split(x,[3,5,7])

[1 2 3 4 5 6 7 8 9]


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [8]:
x=np.arange(1,10).reshape([3,3])
print(x)
np.hsplit(x,3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [18]:
x=np.arange(1,11).reshape([5,2])
print(x)
np.vsplit(x,[4])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10]])]

# Casting

In [19]:
x=np.array([1,2,3,4])
print(x.dtype)
print(x)
y=x.astype(np.float64)
print(y.dtype)
print(y)

int64
[1 2 3 4]
float64
[1. 2. 3. 4.]


In [ ]:
x=np.array(['5.9', '23.3', '4.5']),dtype=x.dtype
