# Numpy -> Numerical Python

1. Numpy is one of the most important foundational package for numerical computing in python.
2. It is an open source python package, that is widely used in science and engineering.
3. The Numpy library contains multi-dimensional array data structure, such as homogenous , n-dimensional (ND) array and a large library of function that operates efficiently on these data structures.

# Why do we use python Numpy?
* We use python Numpy array, instead of list beacuse of the below three reasons:-
  > - less memory
  > - fast
  > - convenient to undertand.
  > - vectorization (way faster than loop in list).

# Why not Python in-built data structure list ?
* A python list stores elements + meta data + pointers -> thus using more memory.
* A Numpy array stores data in a continuous block -> more efficeint and compact.


# Difference between List and Array
* List is an in-built data structure whereas Numpy is a python Library.
* List is slower. Array is faster.
* List store heterogenous data, Array stores Homogenous data structure.
* Numpy library contains multi-dimensional array data structure. Whereas List conatain singke dimensional data structure.

In [2]:
import numpy as np

In [10]:
x=np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
np.__version__

'2.3.4'

In [9]:
arr=np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [12]:
arr=np.array(100)
print(arr)
print(arr.ndim)

100
0


In [13]:
oneD=np.array([1, 2, 3, 4,5])
print(oneD)

print(oneD.ndim)
print(oneD.shape)
print(oneD.size)
print(oneD.itemsize)
print(oneD.dtype)

[1 2 3 4 5]
1
(5,)
5
8
int64


In [14]:
twoD=np.array([[1, 2, 3], [4, 5, 6]])
print(twoD)

print(twoD.ndim)
print(twoD.shape)
print(twoD.size)
print(twoD.itemsize)
print(twoD.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


In [15]:
import numpy as np
threeD=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
m=np.ones(range(0,5))
m

array([], shape=(0, 1, 2, 3, 4), dtype=float64)

In [17]:
u=np.arange(0, 10, 2)
u

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [41]:
import sys as sy

In [56]:
list1=[1, 2, 3, 4, 5, 6, 7, 8, 9]
print(sy.getsizeof(list1))

136


In [57]:
arr=np.array(list1)
print(arr.size*arr.itemsize)
print(arr.nbytes)

72
72


In [58]:
import time as t

In [60]:
l1=range(1,100000)
l2=range(1,100000)
A1=np.array(l1)
A2=np.array(l2)

In [61]:
start=t.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((t.time()-start)*1000)

14.16015625


# Vectorization:
> It means performing operations on entire arrays at once instead of using python loops.

> It is fast as Numpy uses optimized C only internally. -> Works

In [3]:
l1=np.array([1,2,3,4,5])
l2=np.array([1,2,3,4,5])
print(l1+l2)

[ 2  4  6  8 10]


In [4]:
l1=[1,2,3,4,5]
l2=[1,2,3,4,5]
print(l1+l2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


#WITH LISTS, YOU DO OPERATIONS ELEMEMT BY ELEMENT. -> SLOW

#NUMPY ALLOWS ELEMENT WISE OPERATIONS WITHOUT EXPLICIT LOOPS. -> MUCH FASTER

In [6]:
import time as t
arr=np.arange(100000)
lst=[x for x in range(100000)]
start=t.time()
lst2=[x*2 for x in lst]
end=t.time()
print(end - start)

0.005723714828491211


# --> Broadcasting
* -> Operations between different shape arrays
* -> numpy automatically expands the smaller array (without copying), so shapes beome compatible.

In [7]:
a=np.array([1,2,3,4,5])
b=5
print(a+b)

[ 6  7  8  9 10]


In [11]:
arr=np.array([1, 2, 3])
vec=np.array([[1], [2], [3]])
print(arr+vec)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# How to use a python numpy to generate random number
* Random Module
* The random module  in Numpy packag contains many function for generation of random numbers

In [14]:
import random
x=np.random.rand(10)
print(x)
y=np.random.randrange(0, 10)
print(y)

[0.47469713 0.68596618 0.39035052 0.38156445 0.46131647 0.95642184
 0.06803009 0.3529698  0.21800483 0.55591101]


AttributeError: module 'numpy.random' has no attribute 'randrange'

# --> Choice method

In [6]:
import numpy as np
import random
rng=np.random.default_rng()
x=np.random.choice([1,2,3,4,5,6,7,8])
y=rng.choice([1,2,3,4,5,6,7,8])
print(x)
print(y)

8
7


In [10]:
x=np.array([10,23,45,67,89])
print(x[2])
x[2]

45


np.int64(45)

In [15]:
#in multidimensional array, you can specify a comma separated 
y=np.array([[12,23,34], [2,4,67]])
# Method1
print(y[0,2])
# Method2
print(y[0][2])

34
34


In [24]:
x=np.array([10,23,45,67,89])
x[1:4]

array([23, 45, 67])

In [ ]:
y=np.array([[12,23,34], [2,4,67], [1,1,1], [2,2,2]])
y[1:]

array([[ 2,  4, 67],
       [ 1,  1,  1],
       [ 2,  2,  2]])

In [23]:
y[-1:]

array([[2, 2, 2]])

In [26]:
y[-3:-1]

array([[ 2,  4, 67],
       [ 1,  1,  1]])

In [27]:
import numpy as np
arr=np.array([1,2,3,4])
s=arr[1:3]
s[0]=100
print(arr)
print(s)
print(s.base)

[  1 100   3   4]
[100   3]
[  1 100   3   4]
